training:
  batch_size: 200
  n_particle: 200
  particle_lr: 3.0e-4
  n_iter: 3000
  checkpoint_frq: 10
data:
  dataset: compas
  input_dim: 13
  output_dim: 1
model:
  loss_type: mono
  mono_index: [0,1,2,3]
  target_ub: 0.05
  n_hidden: 50
optim:
  alpha_db: 1.0
  max_proj_iter: 20
  eps: 1.0e-8
  diag_mul: 1.3
  alpha_mied: 0.5
